### ISSUE TITLE
Admin team is not added everywhere

### ISSUE THREAD

**Issue by victorb** [ipfs/ci-sync#1]
A couple of weeks ago, me and @diasdavid went through all JavaScript repos and added the Admin team. However, there is still a lot of repos without the admin team, which means that https://github.com/ipfs/ci-sync/blob/master/ci-team-for-all-repos.js won't quite work yet.

Working on a script to get the complete list, then I'll need @lgierth @diasdavid or @whyrusleeping help to add the Admin team everywhere.

**Comment by victorb** [comment]
Added a script for getting a list of repos where the current user don't have access to change settings. https://github.com/ipfs/ci-sync/blob/6ab3a9aadab486f084a61cb86469d7ded299789e/get-repos-with-missing-admin-team.js

Ran it with my own token, which means the repos outputted are missing the Admin team. Sent an email with all repos missing the team.

**Comment by daviddias** [comment]
Done for every org except `gxed` (not an admin there)

**Comment by victorb** [comment]
And done for `gxed`! Thanks @diasdavid @lgierth
