### ISSUE TITLE
Add text to repo description

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/ci-sync#10]
We’re trying to make sure every repo has a description (see ipfs/docs#55) and this repo’s is only a link — we should add some descriptive text to that. I don’t have permissions to add it, but I’d suggest something like:

> 🚚 CI scripts for synchronizing configuration across repos. http://ci-sync.cloud.ipfs.team/ci-status.html

(Adding the truck so this also matches up with ipfs/docs#57)

Side note: the link in the description currently doesn’t work. Is something broken or does it need to be changed?

**Comment by victorb** [comment]
Done, thanks :)

**Comment by victorb** [comment]
Issue with link not working is temporary, it's deployed on a bad host currently
